name: scimap_phenotyping
owner: goeckslab
description: A suite of Galaxy tools for single cell phenotyping and visualizations.

categories:
  - Imaging

remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/scimap_phenotyping

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for scikit learn tool: {{ tool_name }}"
suite:
  name: "scimap_vitessce_tool_suite"
  description: "A suite of Galaxy tools for single cell phenotyping and visualizations"
  
  long_description: |
    Scimap: Spatial Single-Cell Analysis Toolkit. https://scimap.xyz/

    Vitessce: a visual integration tool for exploration of spatial single-cell experiments. http://vitessce.io/

    Squidpy: Spatial Single Cell Analysis in Python. https://squidpy.readthedocs.io/en/stable/