owner: goeckslab
name: s3segmenter
description: "S3segmenter is a Matlab-based set of functions that generates single cell (nuclei and cytoplasm) label masks"
remote_repository_url: https://github.com/HMS-IDAC/S3segmenter
categories: 
  - "Imaging"
