categories:
- Imaging
description: MCMICRO tool suite for Multiplex Tissue Imaging Analysis 
homepage_url: https://github.com/ohsu-comp-bio/mti-tools
name: mcmicro_suite
owner: creason
remote_repository_url: https://github.com/ohsu-comp-bio/mti-tools/tree/master/suites/mcmicro_suite
type: repository_suite_definition 
