owner: goeckslab
name: ashlar
description: "Alignment by Simultaneous Harmonization of Layer/Adjacency Registration
Usage"
remote_repository_url: https://github.com/ohsu-comp-bio/ashlar
categories: 
  - "Imaging"
