owner: watsocam
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/mti-utils/rename_tiff_channels
categories:
  - "Imaging"
repositories:
  rename_tiff_channels:
    description: "Rename channels in OME-TIFF xml metadata"
    include:
      - macros.xml
      - output.xml
      - rename_tiff_channels.xml
      - rename_tiff_channels.py