owner: goeckslab
homepage_url: https://squidpy.readthedocs.io/en/stable/
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/squidpy
categories:
  - CompBio Galaxy Wrappers
repositories:
  squidpy_spatial:
    description: Spatial Single Cell Analysis in Python.
    include:
      - squidpy_spatial.py
      - squidpy_spatial.xml