owner: watsocam
description: "PALOM is a Python module for registering whole-slide images from the same FFPE section with different IHC stainings."
remote_repository_url: https://github.com/goeckslab/tools-mti/tree/main/tools/palom
categories:
  - "Imaging"
